version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: access-postgres
    environment:
      - POSTGRES_DB=cityithack
      - POSTGRES_USER=city
      - POSTGRES_PASSWORD=city
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U city -d cityithack"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: access-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: access-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  dbdata:


