version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cityithack
      POSTGRES_USER: city
      POSTGRES_PASSWORD: city
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U city -d cityithack"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data:


