name: Deploy to VDS (Docker compose over SSH)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to VDS
        run: |
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "mkdir -p /opt/crypto-access"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@gigastack.v6.rocks:/opt/crypto-access/

      - name: Login to Docker registry (optional)
        if: env.DOCKERHUB_USERNAME != ''
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin"

      - name: Build and run docker compose on VDS
        run: |
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "cd /opt/crypto-access && docker compose pull || true && docker compose up -d --build"


