name: Deploy to VDS (Docker compose over SSH)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Копирование исходников на VDS (rsync всего репозитория)
        run: |
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "mkdir -p /opt/crypto-access"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@gigastack.v6.rocks:/opt/crypto-access/

      - name: Сборка backend jar локально и отправка на VDS
        run: |
          ./backend/gradlew -p backend clean build -x test
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "mkdir -p /opt/crypto-access/backend/build/libs"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" backend/build/libs/ root@gigastack.v6.rocks:/opt/crypto-access/backend/build/libs/

      - name: Запуск docker compose на VDS (только backend+postgres)
        run: |
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "cd /opt/crypto-access && docker compose up -d --build backend postgres"

      - name: Сборка фронтенда и выкладка статики на VDS
        run: |
          npm ci --prefix frontend
          npm run build --prefix frontend
          ssh -o StrictHostKeyChecking=no root@gigastack.v6.rocks "mkdir -p /var/www/gigastack"
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" frontend/dist/ root@gigastack.v6.rocks:/var/www/gigastack/


